### ISSUE TITLE
Purview quota reached

### ISSUE THREAD

**Issue by PetarBoshnakov** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#113]
Dear,

We were testing the connector. In our setup we have purview account already in place in the resource group. However, the script produced an error that we reached the tenant quota - which we already had done but the script is not supposed to add a new purview resource if I read it correctly?

Many thanks,
Petar

**Comment by wjohnson** [comment]
Hello, @PetarBoshnakov - Thank you for using the solution accelerator!

If you are following the current ["connector only"](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.1/deploy-base.md) instructions, you should only run the `newdeploymenttemp.json`.

The ["demo deployment"](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.1/deploy-demo.md) has you running the `openlineage-deployment.sh` script which includes deployment of Purview and Databricks.

If you have a Purview account you want to use but NOT a Databricks workspace, please consider deploying a Databricks workspace for you to use and follow the ["connector only"](https://github.com/microsoft/Purview-ADB-Lineage-Solution-Accelerator/blob/release/2.1/deploy-base.md) instructions.  This should prevent the error you're receiving since no Purview account will be deployed.

Please let us know if that resolves your issue.

**Comment by PetarBoshnakov** [comment]
Hi, @wjohnson,

Regarding my first report. We found the cause for the error to be the fact that we have 3 Purview accounts under our subscription that are spread among 2 regions. The connector only deployment script from git(newdeploymenttemp.json) tries to deploy Purview to same location as the resource groups location. If purview already exist in resourceGroup().location, it will skip the deployment of Purview. If it does not exist in resourceGroup().location, it will try to create new Purview instance. To fix it, we hardcoded the location as the deployment location for all objects in the deployment json file. 

Maybe another issue but:
We also got an error for MSDeploy: 

Deployment of below resource failed:

"resources": [

{

"name": "MSDeploy",

"type": "extensions",

"location": "[parameters('location')]",

"apiVersion": "2020-06-01",

"dependsOn": [

"[concat('Microsoft.Web/sites/', variables('functionAppName'))]"

],

"properties": {

"packageUri": "http://aka.ms/APFunctions2-1"

}

}

]

I attached the error screenshots below.

<img width="238" alt="sc1" src="https://user-images.githubusercontent.com/77831092/200255394-2aa33b18-88ea-45f4-90e1-2af6de2d331a.png">
<img width="341" alt="sc2" src="https://user-images.githubusercontent.com/77831092/200255400-0ced346c-ad51-433d-b113-0ac84bfec2e3.png">


To fix this, I downloaded the functions from package URI mentioned deployment json file. Manually uploaded the file to Azure and deployed it manually using az deployment command.

az functionapp deployment source config-zip -g [Resource Group Name] -n functionappdemopurview3mbw --src [user path to scrip]

Many thanks,
Petar

**Comment by wjohnson** [comment]
Thank you, Petar, for sharing your experience and steps that you took to successfully deploy the solution.  I've incorporated your feedback into the above commits.  Thank you so much for taking the time to share how you resolved the issue!
