### ISSUE TITLE
How the incremental changes to a notebook work with the solution ?

### ISSUE THREAD

**Issue by Sam-Panda** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#74]
I am not sure if this is a limitation of the solution or a bug. 

In the sample given notebook, we have exampleInputA and exampleInputB producing the output exampleoutput1. If I replace the exampleInputB with a new input exampleInputC to produce the same output - I get 3 inputs to the notebook in the lineage map where it should have been 2 only ( A&C).  So my question:  does the solution only append and don't delete any lineage mapping?

val exampleC = (
    spark.read.format("csv")
  .schema(exampleCSchema)
  .option("header", true)
  .load(adlsRootPath+"/examples/data/csv/exampleInputC/exampleInputC.csv")
)
val outputDf = exampleA.join(exampleC, exampleA("id") === exampleC("id"), "inner").drop(exampleC("id"))
outputDf.repartition(1).write.mode("overwrite").format("csv").save(adlsRootPath+"/examples/data/csv/exampleOutput/")

Mapping in the purview ( I was expecting exampleInputB to be removed automatically)

![image](https://user-images.githubusercontent.com/29522070/184338093-86dcb83e-c6b7-495e-a522-4c7385f9eb16.png)

**Comment by wjohnson** [comment]
Hi, @Sam-Panda , You can click into the advanced properties of a given notebook and observe individual `databricks processes`. Each process represents a run of the notebook that points to a unique combination of inputs and outputs.  To see a given "state" of lineage, please go to the notebook or notebook task and click on the Properties tab and select one of the processes.  Alternatively, you could look at exampleInputC's lineage view (e.g. switch to the exampleInputC asset) and you should only see `A+C = Output`.

The purpose behind this is to capture historical lineage. For example, if this notebook were parameterized, we'd want to have all history of the inputs and outputs being used (because they were generated / influenced by a given parameter).

Even for notebook that are not parameterized, if you had an object used as an input / written out as an input, you'd still want to note its historical lineage because you want to know how that object was used.

I hope that helps explain why you are seeing this and how you can see your desired view of lineage.

**Comment by wjohnson** [comment]
Closing out since we've answered the question but happy to re-open if necessary.
