### ISSUE TITLE
4 Times the same event by open linage

### ISSUE THREAD

**Issue by rodrigomonteiro-gbb** [microsoft/Purview-ADB-Lineage-Solution-Accelerator#9]
**Describe the bug**
Open linage is sending the same event 4 times
**To Reproduce**
1. Just execute any notebook

**Expected behavior**
We can save some execution and API calls, we should filter repeated events.

**Screenshots**
![image](https://user-images.githubusercontent.com/60233028/173154924-16571c8a-35a9-46da-a668-eaca39f17e36.png)

**Comment by wjohnson** [comment]
@rodrigomonteiro-gbb - Per our conversation, this may be due to the fact that the OpenLineage model emits partial information and it is expected to be aggregated by the end systems.  There may be multiple events but each event might contain a portion of what is necessary to construct lineage.

There is also an OpenLineage issue that may help: https://github.com/OpenLineage/OpenLineage/issues/628

**Comment by wjohnson** [comment]
@rodrigomonteiro-gbb I'm going to close this one for now but we can revisit it if you'd like.
